/*
 * DialogNuevaComanda
 */
package vista;

import controlador.ComandaDB;
import controlador.MiError;
import controlador.MiExcepcion;
import controlador.PlatoDB;
import controlador.Utils;
import java.time.LocalDate;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Comanda;
import modelo.Plato;

/**
 *
 * @author Di Qi
 */
public class DialogNuevaComanda extends javax.swing.JDialog {

    private FramePrincipal padre;
    private Map<Plato, Integer> lineasComanda;
    private int idComanda;
    private float total;

    /**
     * Creates new form DialogNuevaComanda
     */
    public DialogNuevaComanda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.padre = (FramePrincipal) parent;
        this.total = 0;
        tablaLineasComanda.getColumnModel().getColumn(0).setPreferredWidth(255);
        tablaLineasComanda.getColumnModel().getColumn(1).setPreferredWidth(80);

        // Obtener datos por defecto para la nueva comanda
        try {
            idComanda = ComandaDB.getNuevaComandaId();
            lblId.setText(idComanda + "");
            lineasComanda = PlatoDB.getLineasComandaNueva();
        } catch (MiExcepcion ex) {
            JOptionPane.showMessageDialog(this, MiError.getMensaje(ex.getCodigo()));
            this.dispose();
        }

        // Rellenar tabla por defecto
        DefaultTableModel modelo = (DefaultTableModel) tablaLineasComanda.getModel();
        modelo.setRowCount(0);
        for (Plato p : lineasComanda.keySet()) {
            modelo.addRow(new Object[]{p, 0});
        }

        // Listener tabla
        modelo.addTableModelListener((e) -> {
            // Actualiza lineas de comanda
            for (int i = 0; i < modelo.getRowCount(); i++) {
                Plato p = (Plato) modelo.getValueAt(i, 0);
                Integer c = (Integer) modelo.getValueAt(i, 1);
                if (c == null) {
                    c = 0;
                }
                lineasComanda.put(p, c);
            }
            // Actualiza total
            total = 0;
            for (Plato p : lineasComanda.keySet()) {
                total += lineasComanda.get(p) * p.getPrecio();
            }
            lblTotal.setText(Utils.precioStr(total));
        });

        // Fecha por defecto
        datepicker.getComponentDateTextField().setEditable(false);
        datepicker.setDate(LocalDate.now());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtMesa = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        datepicker = new com.github.lgooddatepicker.components.DatePicker();
        txtTotalMaximo = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLineasComanda = new javax.swing.JTable();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear comanda");

        jLabel1.setText("Nº Comanda:");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel2.setText("Nº Mesa:");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel3.setText("Nombre:");
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel4.setText("Fecha:");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel5.setText("Total máximo:");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel6.setText("Total:");
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblId.setText("jLabel7");
        lblId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtMesa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        datepicker.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtTotalMaximo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTotal.setText("0.00 €");
        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tablaLineasComanda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plato", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaLineasComanda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablaLineasComanda.setRowHeight(25);
        jScrollPane1.setViewportView(tablaLineasComanda);

        btnAceptar.setText("Aceptar");
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId)
                            .addComponent(datepicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtMesa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txtTotalMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotal)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(datepicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTotalMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTotal))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        boolean datosCorrectos = true;
        String nombre = txtNombre.getText().trim();
        LocalDate fecha = datepicker.getDate();
        int mesa = -1;
        try {
            mesa = Integer.parseInt(txtMesa.getText().trim());
            if (mesa <= 0) {
                throw new Exception();
            }
        } catch (Exception ex) {
            datosCorrectos = false;
            JOptionPane.showMessageDialog(this, "La mesa tiene que ser un número entero positivo.");
        }
        float totalMaximo = -1;
        try {
            totalMaximo = Float.parseFloat(txtTotalMaximo.getText().trim());
            if (totalMaximo < 0) {
                throw new Exception();
            }
        } catch (Exception ex) {
            datosCorrectos = false;
            JOptionPane.showMessageDialog(this, "El total máximo tiene que ser un número.");
        }

        if (datosCorrectos) {
            if (Float.compare(totalMaximo, total) >= 0) {
                if (Float.compare(total, 0) > 0) {
                    Comanda c = new Comanda(idComanda, mesa, nombre, fecha, total, totalMaximo, padre.getEmpleado());
                    try {
                        ComandaDB.crearComanda(c, lineasComanda);
                        JOptionPane.showMessageDialog(this, "Se ha creado la comanda correctamente.");
                        this.dispose();
                    } catch (MiExcepcion ex) {
                        JOptionPane.showMessageDialog(this, MiError.getMensaje(ex.getCodigo()));
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "La comanda no puede estar vacía.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "El total de la comanda no puede superar el total máximo.");
            }

        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogNuevaComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogNuevaComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogNuevaComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogNuevaComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogNuevaComanda dialog = new DialogNuevaComanda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private com.github.lgooddatepicker.components.DatePicker datepicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tablaLineasComanda;
    private javax.swing.JTextField txtMesa;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTotalMaximo;
    // End of variables declaration//GEN-END:variables
}
