/*
 * PanelComandasIndividual
 */
package vista;

import controlador.ComandaDB;
import controlador.MiError;
import controlador.MiExcepcion;
import controlador.PlatoDB;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Comanda;
import modelo.Plato;

/**
 *
 * @author Di Qi
 */
public class PanelComandasIndividual extends javax.swing.JPanel {

    private FramePrincipal padre;

    private Comanda comanda;
    private Map<Plato, Integer> lineasComanda;

    /**
     * Creates new form PanelComandasIndividual
     */
    public PanelComandasIndividual(FramePrincipal padre) throws MiExcepcion {
        initComponents();

        this.padre = padre;

        ComandaDB.iniciar();

        mostrarComanda();
    }

    /**
     * Mostrar la comanda
     */
    private void mostrarComanda() {
        try {
            // Obtener número de comandas
            int n = ComandaDB.getNumeroComandas();

            if (n > 0) {    // Hay comandas
                // Obtener datos de la base de datos
                comanda = ComandaDB.getComandaActual();
                lineasComanda = PlatoDB.getLineasComanda(comanda);

                // Poner datos de la comanda
                lblId.setText(comanda.getId() + "");
                lblMesa.setText(comanda.getMesa() + "");
                lblNombre.setText(comanda.getNombre());
                lblFecha.setText(comanda.getFechaStr());
                lblTotal.setText(comanda.getTotalStr());
                lblTotalMaximo.setText(comanda.getTotalMaximoStr());

                // Poner datos de las lineas de comanda
                DefaultListModel model = new DefaultListModel<>();
                for (Plato p : lineasComanda.keySet()) {
                    model.addElement(lineasComanda.get(p) + "x " + p);
                }
                listLineasComanda.setModel(model);

                // Actualizar botones
                btnAnterior.setEnabled(!ComandaDB.esPrimera());
                btnPrimera.setEnabled(!ComandaDB.esPrimera());
                btnSiguiente.setEnabled(!ComandaDB.esUltima());
                btnUltima.setEnabled(!ComandaDB.esUltima());
                btnModificar.setEnabled(true);
                btnEliminar.setEnabled(true);
                
            } else {    // No hay comandas
                // Sólo botón Nueva habilitado
                btnAnterior.setEnabled(false);
                btnSiguiente.setEnabled(false);
                btnPrimera.setEnabled(false);
                btnUltima.setEnabled(false);
                btnModificar.setEnabled(false);
                btnEliminar.setEnabled(false);
                
                // Campos vacíos
                lblId.setText("");
                lblMesa.setText("");
                lblNombre.setText("");
                lblFecha.setText("");
                lblTotal.setText("");
                lblTotalMaximo.setText("");
                listLineasComanda.setModel(new DefaultListModel<>());
            }

        } catch (MiExcepcion ex) {
            JOptionPane.showMessageDialog(this, MiError.getMensaje(ex.getCodigo()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblMesa = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblTotalMaximo = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listLineasComanda = new javax.swing.JList<>();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNueva = new javax.swing.JButton();
        btnPrimera = new javax.swing.JButton();
        btnUltima = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nº Comanda:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nº Mesa:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Fecha:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Total máximo:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Total:");

        lblId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblId.setText("Text");

        lblMesa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMesa.setText("Text");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setText("Text");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFecha.setText("Text");

        lblTotalMaximo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotalMaximo.setText("Text");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotal.setText("Text");

        listLineasComanda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listLineasComanda.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listLineasComanda);

        btnAnterior.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNueva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNueva.setText("Nueva");
        btnNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaActionPerformed(evt);
            }
        });

        btnPrimera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPrimera.setText("Primera");
        btnPrimera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeraActionPerformed(evt);
            }
        });

        btnUltima.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUltima.setText("Última");
        btnUltima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId)
                            .addComponent(lblMesa)
                            .addComponent(lblNombre)
                            .addComponent(lblFecha)
                            .addComponent(lblTotalMaximo)
                            .addComponent(lblTotal))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPrimera)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnterior)
                        .addGap(18, 18, 18)
                        .addComponent(btnSiguiente)
                        .addGap(18, 18, 18)
                        .addComponent(btnUltima)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNueva)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblMesa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblTotalMaximo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTotal))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior)
                    .addComponent(btnSiguiente)
                    .addComponent(btnPrimera)
                    .addComponent(btnUltima))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnNueva))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeraActionPerformed
        try {
            ComandaDB.primera();
            mostrarComanda();
        } catch (MiExcepcion ex) {
            JOptionPane.showMessageDialog(this, MiError.getMensaje(ex.getCodigo()));
        }
    }//GEN-LAST:event_btnPrimeraActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        try {
            ComandaDB.anterior();
            mostrarComanda();
        } catch (MiExcepcion ex) {
            JOptionPane.showMessageDialog(this, MiError.getMensaje(ex.getCodigo()));
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        try {
            ComandaDB.siguiente();
            mostrarComanda();
        } catch (MiExcepcion ex) {
            JOptionPane.showMessageDialog(this, MiError.getMensaje(ex.getCodigo()));
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnUltimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimaActionPerformed
        try {
            ComandaDB.ultima();
            mostrarComanda();
        } catch (MiExcepcion ex) {
            JOptionPane.showMessageDialog(this, MiError.getMensaje(ex.getCodigo()));
        }
    }//GEN-LAST:event_btnUltimaActionPerformed

    private void btnNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaActionPerformed
        new DialogNuevaComanda(padre, true).setVisible(true);
        mostrarComanda();
    }//GEN-LAST:event_btnNuevaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            this.comanda = ComandaDB.getComandaActual();
            this.lineasComanda = PlatoDB.getLineasComanda(comanda);
            new DialogModificarComanda(padre, comanda, lineasComanda, true).setVisible(true);
            mostrarComanda();
        } catch (MiExcepcion ex) {
            JOptionPane.showMessageDialog(this, MiError.getMensaje(ex.getCodigo()));
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            ComandaDB.eliminarComanda();
            mostrarComanda();
        } catch (MiExcepcion ex) {
            JOptionPane.showMessageDialog(this, MiError.getMensaje(ex.getCodigo()));
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNueva;
    private javax.swing.JButton btnPrimera;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMesa;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalMaximo;
    private javax.swing.JList<String> listLineasComanda;
    // End of variables declaration//GEN-END:variables
}
